In [1]:
import pandas as pd
import os
import numpy as np

sub_v1 = pd.read_csv('/Users/vigi99/AirtelDEV/MixMatch-pytorch/submission/submission_v1.csv', index_col='fname')
sub_v2 = pd.read_csv('/Users/vigi99/AirtelDEV/MixMatch-pytorch/submission/submission_v2.csv', index_col='fname')
sub_v3 = pd.read_csv('/Users/vigi99/AirtelDEV/MixMatch-pytorch/submission/submission_v3.csv', index_col='fname')
test_path = os.path.abspath('/Users/vigi99/kaggle/freesound/data/test')

def labels_values(df, audio_file, name):
    predicted_labels = df[df.index == audio_file]
    top_5 = np.argsort(predicted_labels.values[0])[-5:].tolist()
    top_5.reverse()
    print("===============")
    print(name)
    print(np.array(predicted_labels.columns)[top_5])
    print(np.array(predicted_labels.values)[0][top_5])
    print("===============")
    print()

In [45]:
random_audio_file = np.random.choice(sub_v1.index.values)
random_audio_file_path = os.path.join(test_path, random_audio_file)
print(random_audio_file_path)
import IPython.display as ipd
labels_values(sub_v1, random_audio_file, 'V1')
labels_values(sub_v2, random_audio_file, 'V2')
labels_values(sub_v3, random_audio_file, 'V3')
ipd.Audio(random_audio_file_path)

/Users/vigi99/kaggle/freesound/data/test/396d793f.wav
V1
['Keys_jangling' 'Crackle' 'Scissors' 'Computer_keyboard' 'Skateboard']
[0.04424074 0.04127118 0.03955373 0.03543916 0.03494359]

V2
['Crackle' 'Computer_keyboard' 'Scissors' 'Writing' 'Purr']
[0.0570731  0.05074305 0.04750921 0.04187033 0.04115737]

V3
['Computer_keyboard' 'Scissors' 'Crackle' 'Keys_jangling' 'Writing']
[0.05625397 0.04838797 0.04539586 0.04345804 0.03777463]



In [14]:
x = sub_v3.idxmax(axis=1)
from collections import Counter
Counter(x.values).most_common()

[('Computer_keyboard', 48),
 ('Stream', 43),
 ('Tick-tock', 38),
 ('Drawer_open_or_close', 36),
 ('Water_tap_and_faucet', 31),
 ('Bicycle_bell', 27),
 ('Bass_drum', 26),
 ('Toilet_flush', 26),
 ('Crackle', 25),
 ('Knock', 25),
 ('Microwave_oven', 25),
 ('Race_car_and_auto_racing', 25),
 ('Shatter', 23),
 ('Cheering', 22),
 ('Female_singing', 22),
 ('Scissors', 22),
 ('Burping_and_eructation', 22),
 ('Zipper_(clothing)', 21),
 ('Electric_guitar', 21),
 ('Harmonica', 20),
 ('Screaming', 20),
 ('Cricket', 19),
 ('Finger_snapping', 18),
 ('Keys_jangling', 17),
 ('Applause', 17),
 ('Meow', 17),
 ('Sneeze', 16),
 ('Run', 16),
 ('Church_bell', 16),
 ('Sigh', 16),
 ('Frying_(food)', 16),
 ('Bass_guitar', 16),
 ('Purr', 16),
 ('Car_passing_by', 15),
 ('Buzz', 14),
 ('Hiss', 14),
 ('Male_singing', 14),
 ('Female_speech_and_woman_speaking', 13),
 ('Chink_and_clink', 12),
 ('Marimba_and_xylophone', 12),
 ('Drip', 11),
 ('Mechanical_fan', 11),
 ('Bark', 11),
 ('Waves_and_surf', 11),
 ('Sink_(fillin

In [15]:
sub_dev = pd.read_csv('/Users/vigi99/AirtelDEV/MixMatch-pytorch/submission/submission_split_train_dev.csv', index_col='fname')
sub_test = pd.read_csv('/Users/vigi99/AirtelDEV/MixMatch-pytorch/submission/submission_split_train_test.csv', index_col='fname')

In [16]:
x = sub_dev.idxmax(axis=1)
from collections import Counter
Counter(x.values).most_common()

[('Car_passing_by', 12),
 ('Crackle', 9),
 ('Meow', 8),
 ('Cricket', 8),
 ('Child_speech_and_kid_speaking', 8),
 ('Drawer_open_or_close', 7),
 ('Stream', 7),
 ('Male_singing', 6),
 ('Sneeze', 6),
 ('Clapping', 6),
 ('Toilet_flush', 6),
 ('Bicycle_bell', 5),
 ('Writing', 5),
 ('Microwave_oven', 5),
 ('Slam', 5),
 ('Fart', 5),
 ('Sigh', 5),
 ('Gurgling', 4),
 ('Female_speech_and_woman_speaking', 4),
 ('Acoustic_guitar', 4),
 ('Marimba_and_xylophone', 4),
 ('Screaming', 4),
 ('Glockenspiel', 4),
 ('Chewing_and_mastication', 4),
 ('Purr', 4),
 ('Buzz', 4),
 ('Skateboard', 4),
 ('Raindrop', 4),
 ('Tick-tock', 4),
 ('Cupboard_open_or_close', 3),
 ('Gasp', 3),
 ('Male_speech_and_man_speaking', 3),
 ('Female_singing', 3),
 ('Fill_(with_liquid)', 3),
 ('Sink_(filling_or_washing)', 3),
 ('Mechanical_fan', 3),
 ('Gong', 3),
 ('Zipper_(clothing)', 3),
 ('Scissors', 3),
 ('Finger_snapping', 3),
 ('Hi-hat', 3),
 ('Computer_keyboard', 2),
 ('Burping_and_eructation', 2),
 ('Bass_drum', 2),
 ('Harmonic

In [17]:
x = sub_test.idxmax(axis=1)
from collections import Counter
Counter(x.values).most_common()

[('Crackle', 10),
 ('Toilet_flush', 9),
 ('Stream', 9),
 ('Bicycle_bell', 8),
 ('Cupboard_open_or_close', 7),
 ('Race_car_and_auto_racing', 7),
 ('Buzz', 6),
 ('Car_passing_by', 6),
 ('Tick-tock', 6),
 ('Gurgling', 6),
 ('Gong', 6),
 ('Writing', 6),
 ('Child_speech_and_kid_speaking', 5),
 ('Bass_guitar', 5),
 ('Clapping', 5),
 ('Mechanical_fan', 5),
 ('Knock', 5),
 ('Whispering', 5),
 ('Chink_and_clink', 4),
 ('Cheering', 4),
 ('Hi-hat', 4),
 ('Water_tap_and_faucet', 4),
 ('Sigh', 4),
 ('Drawer_open_or_close', 4),
 ('Keys_jangling', 4),
 ('Waves_and_surf', 4),
 ('Cricket', 4),
 ('Female_singing', 4),
 ('Male_singing', 4),
 ('Electric_guitar', 4),
 ('Church_bell', 3),
 ('Burping_and_eructation', 3),
 ('Bark', 3),
 ('Frying_(food)', 3),
 ('Microwave_oven', 3),
 ('Scissors', 3),
 ('Glockenspiel', 3),
 ('Harmonica', 3),
 ('Bus', 3),
 ('Printer', 3),
 ('Run', 3),
 ('Yell', 3),
 ('Bass_drum', 3),
 ('Traffic_noise_and_roadway_noise', 3),
 ('Fill_(with_liquid)', 2),
 ('Screaming', 2),
 ('Slam'